name: CUDAtorch_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - conda-forge::python=3.10.18
  - pytorch=2.5.1=cuda126_py310h4acf282_301
  - coffea=2025.7.0
  - setuptools=59.5.0
  - ndcctools
  - conda-pack
  - dill
  - xrootd
  - git
  - pyyaml
  - ipykernel