name: eaf_torch
channels:
  - conda-forge
  - pytorch
dependencies:
  - conda-forge::python=3.10.15
  - pytorch=2.3.1=cuda120_py310h2c91c31_300
  - setuptools=59.5.0
  - numpy=1.23.5
  - coffea=0.7.22
  - fsspec-xrootd
  - ndcctools
  - conda-pack
  - dill
  - xrootd
  - git
  - pyyaml
  - ipykernel