backgroundTrainingPoint:
- 1.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
batchSize: 2000
bkg2gen: 0.6444756888586058
bkg2sm: 1.0
data: /uscms_data/d3/honor/Outputs_sbi/pretraining/modCentral_updated
delta: 1.0e-05
device: cpu
epochs: 40
factor: 0.1
learningRate: 1.0e-05
name: .
network: simple
patience: 10
sig2bkg: 11.02817557123288
sig2gen: 0.6681657463599171
signalTrainingPoint:
- 1.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- -4.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
startingPoint:
- 1.0
- -0.5
- -0.5
- 1.5
- 1.5
- 1.5
- 1.5
- 1.5
- 1.5
- 1.5
- 1.5
- 1.5
- 1.5
- 1.5
- 1.5
- 1.5
- 1.5
wcs:
- ctGIm
- ctGRe
- cQj38
- cQj18
- cQu8
- cQd8
- ctj8
- ctu8
- ctd8
- cQj31
- cQj11
- cQu1
- cQd1
- ctj1
- ctu1
- ctd1
