top1pt:
 min: 0
 max: 1600
 nbins: 40
top2pt: 
 min: 0
 max: 1600
 nbins: 40
top1eta:
 min: -5.
 max: 5.
 nbins: 20
top2eta:
 min: -5.
 max: 5.
 nbins: 20
top1phi:
 min: -3.15
 max: 3.15
 nbins: 20
top2phi:
 min: -3.15
 max: 3.15
 nbins: 20
top1mass:
 min: 152.
 max: 193.
 nbins: 50
top2mass:
 min: 152.
 max: 193.
 nbins: 50
mtt:
 min: 250
 max: 2000
 nbins: 50
tops_pt:
 min: 0
 max: 800
 nbins: 40
avg_top_pt:
 min: 0
 max: 600
 nbins: 40
lep_pt:
 min: 0
 max: 600
 nbins: 40
lep_eta:
 min: -2.5
 max: 2.5
 nbins: 20
lep_phi:
 min: -3.15
 max: 3.15
 nbins: 20
lep_mass:
 min: 0
 max: 200
 nbins: 50
met_pt:
 min: 15
 max: 600
 nbins: 30
met_phi:
 min: -3.15
 max: 3.15
 nbins: 40
jet0_pt:
 min: 0
 max: 1000
 nbins: 50
jet0_eta:
 min: -2.5
 max: 2.5
 nbins: 20
jet0_phi:
 min: -3.15
 max: 3.15
 nbins: 20
jet0_mass:
 min: 0
 max: 200
 nbins: 25
jet1_pt:
 min: 0
 max: 1000
 nbins: 50
jet1_eta:
 min: -2.5
 max: 2.5
 nbins: 20
jet1_phi:
 min: -3.15
 max: 3.15
 nbins: 20
jet1_mass:
 min: 0
 max: 200
 nbins: 50
jet2_pt:
 min: 0
 max: 600
 nbins: 50
jet2_eta:
 min: -2.5
 max: 2.5
 nbins: 20
jet2_phi:
 min: -3.15
 max: 3.15
 nbins: 20
jet2_mass:
 min: 0
 max: 200
 nbins: 50
jet3_pt:
 min: 0
 max: 600
 nbins: 50
jet3_eta:
 min: -2.5
 max: 2.5
 nbins: 20
jet3_phi:
 min: -3.15
 max: 3.15
 nbins: 20
jet3_mass:
 min: 0
 max: 200
 nbins: 50
jet4_pt:
 min: 0
 max: 600
 nbins: 50
jet4_eta:
 min: -2.5
 max: 2.5
 nbins: 20
jet4_phi:
 min: -3.15
 max: 3.15
 nbins: 20
jet4_mass:
 min: 0
 max: 200
 nbins: 50