backgroundTrainingPoint:
- 1.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 1.22
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
batchSize: 1000
device: cuda
epochs: 50
factor: 0.1
learningRate: 1.0e-05
network: simple
patience: 10
startingPoint:
- 1.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 1.22
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
wcs:
- ctGIm
- ctGRe
- cQj38
- cQj18
- cQu8
- cQd8
- ctj8
- ctu8
- ctd8
- cQj31
- cQj11
- cQu1
- cQd1
- ctj1
- ctu1
- ctd1