name: /uscms_data/d3/honor/Outputs_nlo/training/modCentral_revamp_noWgtNorm
signalSample: 
- /uscms/home/honor/nobackup/Outputs_nlo/pretraining/dataframe_TT01j1l_modCentral_tops_.pkl.gz
backgroundSample:
- /uscms/home/honor/nobackup/Outputs_nlo/pretraining/dataframe_2017_TTToSemiLeptonic_partial2_tops_.pkl.gz
signalMetadata:
- /uscms/home/honor/nobackup/Outputs_nlo/pretraining/metadata_TT01j1l_modCentral_tops_.json
backgroundMetadata:
- /uscms/home/honor/nobackup/Outputs_nlo/pretraining/metadata_2017_TTToSemiLeptonic_partial2_tops_.json
device: cuda
network: simple
features: 
- top1pt
- top1eta
- top1phi
- top1mass
- top2pt
- top2eta
- top2phi
- top2mass
batchSize: 1000
epochs: 20
normalization: null
learningRate: 1.0e-05
patience: 10
factor: 0.1
delta: 1.0e-04