name: /uscms_data/d3/honor/Outputs_nlo/training/private_eft_vars
signalSample: /uscms_data/d3/honor/Outputs_nlo/pretraining/dataprep_2017_ctq8_1p22_vars.pkl.gz
backgroundSample: /uscms_data/d3/honor/Outputs_nlo/pretraining/dataprep_2017_TTToSemiLeptonic_partial2_vars_mcut.pkl.gz
device: cuda
network: simple
features: 
- top1pt
- top1eta
- top1phi
- top1mass
- top2pt
- top2eta
- top2phi
- top2mass
batchSize: 1000
epochs: 50
normalization: weightMean
learningRate: 1.0e-05