name: /uscms_data/d3/honor/Outputs_nlo/training/central_eft_all
signalSample: 
- /uscms_data/d3/honor/Outputs_nlo/pretraining/original_dataloader/dataframe_2017_TTtoLNu2Q_0to700.pkl.gz
- /uscms_data/d3/honor/Outputs_nlo/pretraining/original_dataloader/dataframe_2017_TTtoLNu2Q_700to900.pkl.gz
- /uscms_data/d3/honor/Outputs_nlo/pretraining/original_dataloader/dataframe_2017_TTtoLNu2Q_900toInf.pkl.gz
backgroundSample: /uscms_data/d3/honor/Outputs_nlo/pretraining/dataframe_2017_TTToSemiLeptonic_partial.pkl.gz
metadata:
 0to700: /uscms_data/d3/honor/Outputs_nlo/pretraining/original_dataloader/metadata_2017_TTtoLNu2Q_0to700.json
 700to900: /uscms_data/d3/honor/Outputs_nlo/pretraining/original_dataloader/metadata_2017_TTtoLNu2Q_700to900.json
 900toInf: /uscms_data/d3/honor/Outputs_nlo/pretraining/original_dataloader/metadata_2017_TTtoLNu2Q_900toInf.json
 powheg: /uscms_data/d3/honor/Outputs_nlo/pretraining/metadata_2017_TTToSemiLeptonic_partial_vars.json
device: cuda
network: simple
features: 
- top1pt
- top1eta
- top1phi
- top1mass
- top2pt
- top2eta
- top2phi
- top2mass
batchSize: 1000
epochs: 10
normalization: weightMean
learningRate: 1.0e-05